//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;
        ///  &lt;ConfigItem&gt;
        ///    &lt;Section&gt;ActiveFeatures&lt;/Section&gt;
        ///    &lt;Key&gt;Insights&lt;/Key&gt;
        ///    &lt;Value&gt;0&lt;/Value&gt;
        ///  &lt;/ConfigItem&gt;
        ///  &lt;ConfigItem&gt;
        ///    &lt;Section&gt;ActiveFeatures&lt;/Section&gt;
        ///    &lt;Key&gt;Pricing&lt;/Key&gt;
        ///    &lt;Value&gt;1&lt;/Value&gt;
        ///  &lt;/ConfigItem&gt;
        ///  &lt;ConfigItem&gt;
        ///    &lt;Section&gt;ActiveFeatures&lt;/Section&gt;
        ///    &lt;Key&gt;Promotions&lt;/Key&gt;
        ///    &lt;Value&gt;1&lt;/Value&gt;
        ///  &lt;/ConfigItem&gt;
        ///  &lt;ConfigItem&gt;
        ///    &lt;Section&gt;StartScreen&lt;/Section&gt;
        ///    &lt;Key&gt;StartScreen&lt;/Key&gt;
        ///    &lt;Value&gt;Promotions&lt;/Value&gt;
        ///  &lt;/ConfigItem&gt;
        ///&lt;/Results&gt;
        ///.
        /// </summary>
        internal static string ConfigXml {
            get {
                return ResourceManager.GetString("ConfigXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Measure&gt;&lt;ID&gt;1&lt;/ID&gt;&lt;DisplayName&gt;Distribution Cse&lt;/DisplayName&gt;&lt;IsSelected&gt;1&lt;/IsSelected&gt;&lt;EditableFromDate&gt;2010-11-01T00:00:00&lt;/EditableFromDate&gt;&lt;EditableToDate&gt;2011-12-21T00:00:00&lt;/EditableToDate&gt;&lt;/Measure&gt;&lt;Measure&gt;&lt;ID&gt;2&lt;/ID&gt;&lt;DisplayName&gt;Baseline Distribution Cse&lt;/DisplayName&gt;&lt;IsSelected&gt;1&lt;/IsSelected&gt;&lt;EditableFromDate&gt;2010-11-01T00:00:00&lt;/EditableFromDate&gt;&lt;EditableToDate&gt;2011-12-21T00:00:00&lt;/EditableToDate&gt;&lt;/Measure&gt;&lt;Measure&gt;&lt;ID&gt;3&lt;/ID&gt;&lt;DisplayName&gt;VROS Sgl&lt;/DisplayName&gt;&lt;IsSelected&gt;1&lt;/IsSelected&gt;&lt;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MeasureDataXml {
            get {
                return ResourceManager.GetString("MeasureDataXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;
        ///  &lt;Row&gt;
        ///    &lt;Product&gt;12517&lt;/Product&gt;
        ///    &lt;Measure&gt;1&lt;/Measure&gt;
        ///    &lt;Format&gt;N0&lt;/Format&gt;
        ///    &lt;AggrType&gt;SUM&lt;/AggrType&gt;
        ///    &lt;IsSelectedInChart&gt;1&lt;/IsSelectedInChart&gt;
        ///    &lt;Values&gt;
        ///      &lt;Value&gt;
        ///        &lt;Column&gt;
        ///          &lt;ID&gt;201003&lt;/ID&gt;
        ///          &lt;Name&gt;Wk 3&lt;/Name&gt;
        ///        &lt;/Column&gt;
        ///        &lt;Data&gt;1.1&lt;/Data&gt;
        ///        &lt;IsEditable&gt;0&lt;/IsEditable&gt;
        ///        &lt;Colour&gt;#FFFFFF&lt;/Colour&gt;
        ///        &lt;IsBold&gt;0&lt;/IsBold&gt;
        ///      &lt;/Value&gt;
        ///      &lt;Value&gt;
        ///        &lt;Column&gt;
        ///          &lt;ID&gt;201004&lt;/ID&gt;
        ///          &lt;Na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoreNestedPlanningDataXml {
            get {
                return ResourceManager.GetString("MoreNestedPlanningDataXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;
        ///  &lt;Row&gt;
        ///    &lt;Product&gt;1017&lt;/Product&gt;
        ///    &lt;Measure&gt;1&lt;/Measure&gt;
        ///    &lt;Format&gt;N0&lt;/Format&gt;
        ///    &lt;AggrType&gt;AVG&lt;/AggrType&gt;
        ///    &lt;IsSelectedInChart&gt;1&lt;/IsSelectedInChart&gt;
        ///    &lt;Values&gt;
        ///      &lt;Value&gt;
        ///        &lt;Column&gt;
        ///          &lt;ID&gt;20110101&lt;/ID&gt;
        ///          &lt;Name&gt;Jan:2011&lt;/Name&gt;
        ///        &lt;/Column&gt;
        ///        &lt;Data&gt;0.0000&lt;/Data&gt;
        ///        &lt;IsEditable&gt;0&lt;/IsEditable&gt;
        ///        &lt;Colour&gt;#f5f1f1&lt;/Colour&gt;
        ///        &lt;IsBold&gt;0&lt;/IsBold&gt;
        ///        &lt;Comment /&gt;
        ///      &lt;/Value&gt;
        ///      &lt;Value&gt;
        ///        &lt;Column&gt;
        ///          &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlanningDataXml {
            get {
                return ResourceManager.GetString("PlanningDataXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Results&gt;&lt;Product&gt;&lt;ID&gt;0&lt;/ID&gt;&lt;DisplayName&gt;All&lt;/DisplayName&gt;&lt;ParentID&gt;&lt;/ParentID&gt;&lt;IsSelected&gt;0&lt;/IsSelected&gt;&lt;/Product&gt;&lt;Product&gt;&lt;ID&gt;2&lt;/ID&gt;&lt;DisplayName&gt;BISCUITS&lt;/DisplayName&gt;&lt;ParentID&gt;0&lt;/ParentID&gt;&lt;IsSelected&gt;0&lt;/IsSelected&gt;&lt;/Product&gt;&lt;Product&gt;&lt;ID&gt;3&lt;/ID&gt;&lt;DisplayName&gt;CEREALS&lt;/DisplayName&gt;&lt;ParentID&gt;0&lt;/ParentID&gt;&lt;IsSelected&gt;0&lt;/IsSelected&gt;&lt;/Product&gt;&lt;Product&gt;&lt;ID&gt;4&lt;/ID&gt;&lt;DisplayName&gt;DAIRY&lt;/DisplayName&gt;&lt;ParentID&gt;0&lt;/ParentID&gt;&lt;IsSelected&gt;0&lt;/IsSelected&gt;&lt;/Product&gt;&lt;Product&gt;&lt;ID&gt;5&lt;/ID&gt;&lt;DisplayName&gt;SAVOURY SNACKS&lt;/DisplayName&gt;&lt;Pare [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductDataXml {
            get {
                return ResourceManager.GetString("ProductDataXml", resourceCulture);
            }
        }
    }
}
