#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigTool
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ESP_Demo_DEV_UK_v2_9")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSYS_Config(SYS_Config instance);
    partial void UpdateSYS_Config(SYS_Config instance);
    partial void DeleteSYS_Config(SYS_Config instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConfigTool.Properties.Settings.Default.ESP_Demo_DEV_UK_v2_9ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYS_Config> SYS_Configs
		{
			get
			{
				return this.GetTable<SYS_Config>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.SYS_Config")]
	public partial class SYS_Config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OptionItem_ID;
		
		private string _OptionItem;
		
		private string _OptionItemDetail;
		
		private string _OptionItemDetail_Value;
		
		private string _Description;
		
		private bool _IsEditable;
		
		private string _MenuItem_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOptionItem_IDChanging(int value);
    partial void OnOptionItem_IDChanged();
    partial void OnOptionItemChanging(string value);
    partial void OnOptionItemChanged();
    partial void OnOptionItemDetailChanging(string value);
    partial void OnOptionItemDetailChanged();
    partial void OnOptionItemDetail_ValueChanging(string value);
    partial void OnOptionItemDetail_ValueChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsEditableChanging(bool value);
    partial void OnIsEditableChanged();
    partial void OnMenuItem_CodeChanging(string value);
    partial void OnMenuItem_CodeChanged();
    #endregion
		
		public SYS_Config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItem_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OptionItem_ID
		{
			get
			{
				return this._OptionItem_ID;
			}
			set
			{
				if ((this._OptionItem_ID != value))
				{
					this.OnOptionItem_IDChanging(value);
					this.SendPropertyChanging();
					this._OptionItem_ID = value;
					this.SendPropertyChanged("OptionItem_ID");
					this.OnOptionItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItem", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OptionItem
		{
			get
			{
				return this._OptionItem;
			}
			set
			{
				if ((this._OptionItem != value))
				{
					this.OnOptionItemChanging(value);
					this.SendPropertyChanging();
					this._OptionItem = value;
					this.SendPropertyChanged("OptionItem");
					this.OnOptionItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItemDetail", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OptionItemDetail
		{
			get
			{
				return this._OptionItemDetail;
			}
			set
			{
				if ((this._OptionItemDetail != value))
				{
					this.OnOptionItemDetailChanging(value);
					this.SendPropertyChanging();
					this._OptionItemDetail = value;
					this.SendPropertyChanged("OptionItemDetail");
					this.OnOptionItemDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItemDetail_Value", DbType="NVarChar(4000)")]
		public string OptionItemDetail_Value
		{
			get
			{
				return this._OptionItemDetail_Value;
			}
			set
			{
				if ((this._OptionItemDetail_Value != value))
				{
					this.OnOptionItemDetail_ValueChanging(value);
					this.SendPropertyChanging();
					this._OptionItemDetail_Value = value;
					this.SendPropertyChanged("OptionItemDetail_Value");
					this.OnOptionItemDetail_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEditable", DbType="Bit NOT NULL")]
		public bool IsEditable
		{
			get
			{
				return this._IsEditable;
			}
			set
			{
				if ((this._IsEditable != value))
				{
					this.OnIsEditableChanging(value);
					this.SendPropertyChanging();
					this._IsEditable = value;
					this.SendPropertyChanged("IsEditable");
					this.OnIsEditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItem_Code", DbType="VarChar(50)")]
		public string MenuItem_Code
		{
			get
			{
				return this._MenuItem_Code;
			}
			set
			{
				if ((this._MenuItem_Code != value))
				{
					this.OnMenuItem_CodeChanging(value);
					this.SendPropertyChanging();
					this._MenuItem_Code = value;
					this.SendPropertyChanged("MenuItem_Code");
					this.OnMenuItem_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
