#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exceedra.DB.DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ESP_Demo_DEV_FoodDrink_v2_8")]
	public partial class ExceedraDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFact_User_Alert_Group(Fact_User_Alert_Group instance);
    partial void UpdateFact_User_Alert_Group(Fact_User_Alert_Group instance);
    partial void DeleteFact_User_Alert_Group(Fact_User_Alert_Group instance);
    partial void InsertFact_User_Scenario(Fact_User_Scenario instance);
    partial void UpdateFact_User_Scenario(Fact_User_Scenario instance);
    partial void DeleteFact_User_Scenario(Fact_User_Scenario instance);
    partial void InsertFact_User_Analytic(Fact_User_Analytic instance);
    partial void UpdateFact_User_Analytic(Fact_User_Analytic instance);
    partial void DeleteFact_User_Analytic(Fact_User_Analytic instance);
    partial void InsertFact_User_Canvas_Report(Fact_User_Canvas_Report instance);
    partial void UpdateFact_User_Canvas_Report(Fact_User_Canvas_Report instance);
    partial void DeleteFact_User_Canvas_Report(Fact_User_Canvas_Report instance);
    partial void InsertFact_User_Customer(Fact_User_Customer instance);
    partial void UpdateFact_User_Customer(Fact_User_Customer instance);
    partial void DeleteFact_User_Customer(Fact_User_Customer instance);
    partial void InsertFact_User_Login_Log(Fact_User_Login_Log instance);
    partial void UpdateFact_User_Login_Log(Fact_User_Login_Log instance);
    partial void DeleteFact_User_Login_Log(Fact_User_Login_Log instance);
    partial void InsertFact_User_Product(Fact_User_Product instance);
    partial void UpdateFact_User_Product(Fact_User_Product instance);
    partial void DeleteFact_User_Product(Fact_User_Product instance);
    partial void InsertFact_User_Promotion_Graph(Fact_User_Promotion_Graph instance);
    partial void UpdateFact_User_Promotion_Graph(Fact_User_Promotion_Graph instance);
    partial void DeleteFact_User_Promotion_Graph(Fact_User_Promotion_Graph instance);
    partial void InsertFact_User_Report(Fact_User_Report instance);
    partial void UpdateFact_User_Report(Fact_User_Report instance);
    partial void DeleteFact_User_Report(Fact_User_Report instance);
    partial void InsertFact_User_Role(Fact_User_Role instance);
    partial void UpdateFact_User_Role(Fact_User_Role instance);
    partial void DeleteFact_User_Role(Fact_User_Role instance);
    partial void InsertFact_User_SalesOrg(Fact_User_SalesOrg instance);
    partial void UpdateFact_User_SalesOrg(Fact_User_SalesOrg instance);
    partial void DeleteFact_User_SalesOrg(Fact_User_SalesOrg instance);
    partial void InsertDim_User(Dim_User instance);
    partial void UpdateDim_User(Dim_User instance);
    partial void DeleteDim_User(Dim_User instance);
    partial void InsertSYS_Config(SYS_Config instance);
    partial void UpdateSYS_Config(SYS_Config instance);
    partial void DeleteSYS_Config(SYS_Config instance);
    #endregion
		
		public ExceedraDBDataContext() : 
				base(global::Exceedra.DB.Properties.Settings.Default.ESP_Demo_DEV_FoodDrink_v2_8ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExceedraDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExceedraDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExceedraDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExceedraDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fact_User_Alert_Group> Fact_User_Alert_Groups
		{
			get
			{
				return this.GetTable<Fact_User_Alert_Group>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Scenario> Fact_User_Scenarios
		{
			get
			{
				return this.GetTable<Fact_User_Scenario>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Analytic> Fact_User_Analytics
		{
			get
			{
				return this.GetTable<Fact_User_Analytic>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Canvas_Report> Fact_User_Canvas_Reports
		{
			get
			{
				return this.GetTable<Fact_User_Canvas_Report>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Customer> Fact_User_Customers
		{
			get
			{
				return this.GetTable<Fact_User_Customer>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Login_Log> Fact_User_Login_Logs
		{
			get
			{
				return this.GetTable<Fact_User_Login_Log>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Product> Fact_User_Products
		{
			get
			{
				return this.GetTable<Fact_User_Product>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Promotion_Graph> Fact_User_Promotion_Graphs
		{
			get
			{
				return this.GetTable<Fact_User_Promotion_Graph>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Report> Fact_User_Reports
		{
			get
			{
				return this.GetTable<Fact_User_Report>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_Role> Fact_User_Roles
		{
			get
			{
				return this.GetTable<Fact_User_Role>();
			}
		}
		
		public System.Data.Linq.Table<Fact_User_SalesOrg> Fact_User_SalesOrgs
		{
			get
			{
				return this.GetTable<Fact_User_SalesOrg>();
			}
		}
		
		public System.Data.Linq.Table<Dim_User> Dim_Users
		{
			get
			{
				return this.GetTable<Dim_User>();
			}
		}
		
		public System.Data.Linq.Table<SYS_Config> SYS_Configs
		{
			get
			{
				return this.GetTable<SYS_Config>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.Procast_SP_DUMMY_GetHorizontalGrid", IsComposable=true)]
		public object Procast_SP_DUMMY_GetHorizontalGrid([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML_In", DbType="Xml")] System.Xml.Linq.XElement xML_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBUG_MODE", DbType="Int")] System.Nullable<int> dEBUG_MODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_TEST_MODE", DbType="Bit")] System.Nullable<bool> uNIT_TEST_MODE)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML_In, dEBUG_MODE, uNIT_TEST_MODE).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.Procast_SP_UserLanguage", IsComposable=true)]
		public object Procast_SP_UserLanguage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML_In", DbType="Xml")] System.Xml.Linq.XElement xML_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBUG_MODE", DbType="Int")] System.Nullable<int> dEBUG_MODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_TEST_MODE", DbType="Bit")] System.Nullable<bool> uNIT_TEST_MODE)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML_In, dEBUG_MODE, uNIT_TEST_MODE).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.Procast_SP_UserPref_Save", IsComposable=true)]
		public object Procast_SP_UserPref_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML_In", DbType="Xml")] System.Xml.Linq.XElement xML_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBUG_MODE", DbType="Int")] System.Nullable<int> dEBUG_MODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_TEST_MODE", DbType="Bit")] System.Nullable<bool> uNIT_TEST_MODE)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML_In, dEBUG_MODE, uNIT_TEST_MODE).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.Procast_SP_LOGIN_User_Login", IsComposable=true)]
		public object Procast_SP_LOGIN_User_Login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML_In", DbType="Xml")] System.Xml.Linq.XElement xML_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBUG_MODE", DbType="Int")] System.Nullable<int> dEBUG_MODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_TEST_MODE", DbType="Bit")] System.Nullable<bool> uNIT_TEST_MODE)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML_In, dEBUG_MODE, uNIT_TEST_MODE).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.Procast_SP_LOGIN_GetSysConfig", IsComposable=true)]
		public object Procast_SP_LOGIN_GetSysConfig([global::System.Data.Linq.Mapping.ParameterAttribute(Name="XML_In", DbType="Xml")] System.Xml.Linq.XElement xML_In, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEBUG_MODE", DbType="Int")] System.Nullable<int> dEBUG_MODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_TEST_MODE", DbType="Bit")] System.Nullable<bool> uNIT_TEST_MODE)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), xML_In, dEBUG_MODE, uNIT_TEST_MODE).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Alert_Group")]
	public partial class Fact_User_Alert_Group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Alert_Group_Idx;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnAlert_Group_IdxChanging(int value);
    partial void OnAlert_Group_IdxChanged();
    #endregion
		
		public Fact_User_Alert_Group()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alert_Group_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Alert_Group_Idx
		{
			get
			{
				return this._Alert_Group_Idx;
			}
			set
			{
				if ((this._Alert_Group_Idx != value))
				{
					this.OnAlert_Group_IdxChanging(value);
					this.SendPropertyChanging();
					this._Alert_Group_Idx = value;
					this.SendPropertyChanged("Alert_Group_Idx");
					this.OnAlert_Group_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Alert_Group", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Alert_Groups.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Alert_Groups.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Scenario")]
	public partial class Fact_User_Scenario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Scen_Idx;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnScen_IdxChanging(int value);
    partial void OnScen_IdxChanged();
    #endregion
		
		public Fact_User_Scenario()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scen_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Scen_Idx
		{
			get
			{
				return this._Scen_Idx;
			}
			set
			{
				if ((this._Scen_Idx != value))
				{
					this.OnScen_IdxChanging(value);
					this.SendPropertyChanging();
					this._Scen_Idx = value;
					this.SendPropertyChanged("Scen_Idx");
					this.OnScen_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Scenario", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Scenarios.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Scenarios.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Analytics")]
	public partial class Fact_User_Analytic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _AnalyticsReport_Idx;
		
		private bool _Report_IsDefault;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnAnalyticsReport_IdxChanging(int value);
    partial void OnAnalyticsReport_IdxChanged();
    partial void OnReport_IsDefaultChanging(bool value);
    partial void OnReport_IsDefaultChanged();
    #endregion
		
		public Fact_User_Analytic()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalyticsReport_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AnalyticsReport_Idx
		{
			get
			{
				return this._AnalyticsReport_Idx;
			}
			set
			{
				if ((this._AnalyticsReport_Idx != value))
				{
					this.OnAnalyticsReport_IdxChanging(value);
					this.SendPropertyChanging();
					this._AnalyticsReport_Idx = value;
					this.SendPropertyChanged("AnalyticsReport_Idx");
					this.OnAnalyticsReport_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_IsDefault", DbType="Bit NOT NULL")]
		public bool Report_IsDefault
		{
			get
			{
				return this._Report_IsDefault;
			}
			set
			{
				if ((this._Report_IsDefault != value))
				{
					this.OnReport_IsDefaultChanging(value);
					this.SendPropertyChanging();
					this._Report_IsDefault = value;
					this.SendPropertyChanged("Report_IsDefault");
					this.OnReport_IsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Analytic", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Analytics.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Analytics.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Canvas_Report")]
	public partial class Fact_User_Canvas_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Canvas_Report_Idx;
		
		private bool _Report_Is_Default;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnCanvas_Report_IdxChanging(int value);
    partial void OnCanvas_Report_IdxChanged();
    partial void OnReport_Is_DefaultChanging(bool value);
    partial void OnReport_Is_DefaultChanged();
    #endregion
		
		public Fact_User_Canvas_Report()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Canvas_Report_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Canvas_Report_Idx
		{
			get
			{
				return this._Canvas_Report_Idx;
			}
			set
			{
				if ((this._Canvas_Report_Idx != value))
				{
					this.OnCanvas_Report_IdxChanging(value);
					this.SendPropertyChanging();
					this._Canvas_Report_Idx = value;
					this.SendPropertyChanged("Canvas_Report_Idx");
					this.OnCanvas_Report_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Is_Default", DbType="Bit NOT NULL")]
		public bool Report_Is_Default
		{
			get
			{
				return this._Report_Is_Default;
			}
			set
			{
				if ((this._Report_Is_Default != value))
				{
					this.OnReport_Is_DefaultChanging(value);
					this.SendPropertyChanging();
					this._Report_Is_Default = value;
					this.SendPropertyChanged("Report_Is_Default");
					this.OnReport_Is_DefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Canvas_Report", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Canvas_Reports.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Canvas_Reports.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Customers")]
	public partial class Fact_User_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Cust_Idx;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnCust_IdxChanging(int value);
    partial void OnCust_IdxChanged();
    #endregion
		
		public Fact_User_Customer()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cust_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Cust_Idx
		{
			get
			{
				return this._Cust_Idx;
			}
			set
			{
				if ((this._Cust_Idx != value))
				{
					this.OnCust_IdxChanging(value);
					this.SendPropertyChanging();
					this._Cust_Idx = value;
					this.SendPropertyChanged("Cust_Idx");
					this.OnCust_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Customer", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Customers.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Customers.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Login_Log")]
	public partial class Fact_User_Login_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Login_Log_Idx;
		
		private System.Nullable<int> _User_Idx;
		
		private string _User_ADName;
		
		private System.DateTime _DateTimeStamp;
		
		private bool _Login_Success;
		
		private string _SUser_SName;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogin_Log_IdxChanging(int value);
    partial void OnLogin_Log_IdxChanged();
    partial void OnUser_IdxChanging(System.Nullable<int> value);
    partial void OnUser_IdxChanged();
    partial void OnUser_ADNameChanging(string value);
    partial void OnUser_ADNameChanged();
    partial void OnDateTimeStampChanging(System.DateTime value);
    partial void OnDateTimeStampChanged();
    partial void OnLogin_SuccessChanging(bool value);
    partial void OnLogin_SuccessChanged();
    partial void OnSUser_SNameChanging(string value);
    partial void OnSUser_SNameChanged();
    #endregion
		
		public Fact_User_Login_Log()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_Log_Idx", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Login_Log_Idx
		{
			get
			{
				return this._Login_Log_Idx;
			}
			set
			{
				if ((this._Login_Log_Idx != value))
				{
					this.OnLogin_Log_IdxChanging(value);
					this.SendPropertyChanging();
					this._Login_Log_Idx = value;
					this.SendPropertyChanged("Login_Log_Idx");
					this.OnLogin_Log_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int")]
		public System.Nullable<int> User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ADName", DbType="NVarChar(256)")]
		public string User_ADName
		{
			get
			{
				return this._User_ADName;
			}
			set
			{
				if ((this._User_ADName != value))
				{
					this.OnUser_ADNameChanging(value);
					this.SendPropertyChanging();
					this._User_ADName = value;
					this.SendPropertyChanged("User_ADName");
					this.OnUser_ADNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this.OnDateTimeStampChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStamp = value;
					this.SendPropertyChanged("DateTimeStamp");
					this.OnDateTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_Success", DbType="Bit NOT NULL")]
		public bool Login_Success
		{
			get
			{
				return this._Login_Success;
			}
			set
			{
				if ((this._Login_Success != value))
				{
					this.OnLogin_SuccessChanging(value);
					this.SendPropertyChanging();
					this._Login_Success = value;
					this.SendPropertyChanged("Login_Success");
					this.OnLogin_SuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUser_SName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SUser_SName
		{
			get
			{
				return this._SUser_SName;
			}
			set
			{
				if ((this._SUser_SName != value))
				{
					this.OnSUser_SNameChanging(value);
					this.SendPropertyChanging();
					this._SUser_SName = value;
					this.SendPropertyChanged("SUser_SName");
					this.OnSUser_SNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Login_Log", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Login_Logs.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Login_Logs.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Product")]
	public partial class Fact_User_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Sku_Idx;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnSku_IdxChanging(int value);
    partial void OnSku_IdxChanged();
    #endregion
		
		public Fact_User_Product()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sku_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Sku_Idx
		{
			get
			{
				return this._Sku_Idx;
			}
			set
			{
				if ((this._Sku_Idx != value))
				{
					this.OnSku_IdxChanging(value);
					this.SendPropertyChanging();
					this._Sku_Idx = value;
					this.SendPropertyChanged("Sku_Idx");
					this.OnSku_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Product", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Products.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Products.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Promotion_Graph")]
	public partial class Fact_User_Promotion_Graph : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Promotion_Graph_Idx;
		
		private bool _IsDefault;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnPromotion_Graph_IdxChanging(int value);
    partial void OnPromotion_Graph_IdxChanged();
    partial void OnIsDefaultChanging(bool value);
    partial void OnIsDefaultChanged();
    #endregion
		
		public Fact_User_Promotion_Graph()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promotion_Graph_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Promotion_Graph_Idx
		{
			get
			{
				return this._Promotion_Graph_Idx;
			}
			set
			{
				if ((this._Promotion_Graph_Idx != value))
				{
					this.OnPromotion_Graph_IdxChanging(value);
					this.SendPropertyChanging();
					this._Promotion_Graph_Idx = value;
					this.SendPropertyChanged("Promotion_Graph_Idx");
					this.OnPromotion_Graph_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Promotion_Graph", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Promotion_Graphs.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Promotion_Graphs.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Reports")]
	public partial class Fact_User_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Report_Idx;
		
		private int _Report_IsDefault;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnReport_IdxChanging(int value);
    partial void OnReport_IdxChanged();
    partial void OnReport_IsDefaultChanging(int value);
    partial void OnReport_IsDefaultChanged();
    #endregion
		
		public Fact_User_Report()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Report_Idx
		{
			get
			{
				return this._Report_Idx;
			}
			set
			{
				if ((this._Report_Idx != value))
				{
					this.OnReport_IdxChanging(value);
					this.SendPropertyChanging();
					this._Report_Idx = value;
					this.SendPropertyChanged("Report_Idx");
					this.OnReport_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report_IsDefault", DbType="Int NOT NULL")]
		public int Report_IsDefault
		{
			get
			{
				return this._Report_IsDefault;
			}
			set
			{
				if ((this._Report_IsDefault != value))
				{
					this.OnReport_IsDefaultChanging(value);
					this.SendPropertyChanging();
					this._Report_IsDefault = value;
					this.SendPropertyChanged("Report_IsDefault");
					this.OnReport_IsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Report", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Reports.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Reports.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_Roles")]
	public partial class Fact_User_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _Role_Idx;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnRole_IdxChanging(int value);
    partial void OnRole_IdxChanged();
    #endregion
		
		public Fact_User_Role()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Role_Idx
		{
			get
			{
				return this._Role_Idx;
			}
			set
			{
				if ((this._Role_Idx != value))
				{
					this.OnRole_IdxChanging(value);
					this.SendPropertyChanging();
					this._Role_Idx = value;
					this.SendPropertyChanged("Role_Idx");
					this.OnRole_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Role", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_Roles.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_Roles.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Fact_User_SalesOrg")]
	public partial class Fact_User_SalesOrg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private int _SalesOrg_Idx;
		
		private System.Nullable<bool> _IsDefault;
		
		private EntityRef<Dim_User> _Dim_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnSalesOrg_IdxChanging(int value);
    partial void OnSalesOrg_IdxChanged();
    partial void OnIsDefaultChanging(System.Nullable<bool> value);
    partial void OnIsDefaultChanged();
    #endregion
		
		public Fact_User_SalesOrg()
		{
			this._Dim_User = default(EntityRef<Dim_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					if (this._Dim_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalesOrg_Idx", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SalesOrg_Idx
		{
			get
			{
				return this._SalesOrg_Idx;
			}
			set
			{
				if ((this._SalesOrg_Idx != value))
				{
					this.OnSalesOrg_IdxChanging(value);
					this.SendPropertyChanging();
					this._SalesOrg_Idx = value;
					this.SendPropertyChanged("SalesOrg_Idx");
					this.OnSalesOrg_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit")]
		public System.Nullable<bool> IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_SalesOrg", Storage="_Dim_User", ThisKey="User_Idx", OtherKey="User_Idx", IsForeignKey=true)]
		public Dim_User Dim_User
		{
			get
			{
				return this._Dim_User.Entity;
			}
			set
			{
				Dim_User previousValue = this._Dim_User.Entity;
				if (((previousValue != value) 
							|| (this._Dim_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dim_User.Entity = null;
						previousValue.Fact_User_SalesOrgs.Remove(this);
					}
					this._Dim_User.Entity = value;
					if ((value != null))
					{
						value.Fact_User_SalesOrgs.Add(this);
						this._User_Idx = value.User_Idx;
					}
					else
					{
						this._User_Idx = default(int);
					}
					this.SendPropertyChanged("Dim_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.Dim_Users")]
	public partial class Dim_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Idx;
		
		private string _User_FirstName;
		
		private string _User_LastName;
		
		private string _User_DisplayName;
		
		private string _User_Email;
		
		private string _User_LoginName;
		
		private string _User_LoginPassword;
		
		private string _User_Hash;
		
		private string _User_SaltedPassword;
		
		private string _User_UniqueCode;
		
		private bool _User_ExcludeFromEmail_Workflow;
		
		private string _User_AD_Name;
		
		private bool _IsEnabled;
		
		private bool _IsUserProfile;
		
		private System.Nullable<int> _AssignedProfile_Idx;
		
		private string _User_Language;
		
		private System.Nullable<System.Guid> _SessionID;
		
		private EntitySet<Fact_User_Alert_Group> _Fact_User_Alert_Groups;
		
		private EntitySet<Fact_User_Scenario> _Fact_User_Scenarios;
		
		private EntitySet<Fact_User_Analytic> _Fact_User_Analytics;
		
		private EntitySet<Fact_User_Canvas_Report> _Fact_User_Canvas_Reports;
		
		private EntitySet<Fact_User_Customer> _Fact_User_Customers;
		
		private EntitySet<Fact_User_Login_Log> _Fact_User_Login_Logs;
		
		private EntitySet<Fact_User_Product> _Fact_User_Products;
		
		private EntitySet<Fact_User_Promotion_Graph> _Fact_User_Promotion_Graphs;
		
		private EntitySet<Fact_User_Report> _Fact_User_Reports;
		
		private EntitySet<Fact_User_Role> _Fact_User_Roles;
		
		private EntitySet<Fact_User_SalesOrg> _Fact_User_SalesOrgs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdxChanging(int value);
    partial void OnUser_IdxChanged();
    partial void OnUser_FirstNameChanging(string value);
    partial void OnUser_FirstNameChanged();
    partial void OnUser_LastNameChanging(string value);
    partial void OnUser_LastNameChanged();
    partial void OnUser_DisplayNameChanging(string value);
    partial void OnUser_DisplayNameChanged();
    partial void OnUser_EmailChanging(string value);
    partial void OnUser_EmailChanged();
    partial void OnUser_LoginNameChanging(string value);
    partial void OnUser_LoginNameChanged();
    partial void OnUser_LoginPasswordChanging(string value);
    partial void OnUser_LoginPasswordChanged();
    partial void OnUser_HashChanging(string value);
    partial void OnUser_HashChanged();
    partial void OnUser_SaltedPasswordChanging(string value);
    partial void OnUser_SaltedPasswordChanged();
    partial void OnUser_UniqueCodeChanging(string value);
    partial void OnUser_UniqueCodeChanged();
    partial void OnUser_ExcludeFromEmail_WorkflowChanging(bool value);
    partial void OnUser_ExcludeFromEmail_WorkflowChanged();
    partial void OnUser_AD_NameChanging(string value);
    partial void OnUser_AD_NameChanged();
    partial void OnIsEnabledChanging(bool value);
    partial void OnIsEnabledChanged();
    partial void OnIsUserProfileChanging(bool value);
    partial void OnIsUserProfileChanged();
    partial void OnAssignedProfile_IdxChanging(System.Nullable<int> value);
    partial void OnAssignedProfile_IdxChanged();
    partial void OnUser_LanguageChanging(string value);
    partial void OnUser_LanguageChanged();
    partial void OnSessionIDChanging(System.Nullable<System.Guid> value);
    partial void OnSessionIDChanged();
    #endregion
		
		public Dim_User()
		{
			this._Fact_User_Alert_Groups = new EntitySet<Fact_User_Alert_Group>(new Action<Fact_User_Alert_Group>(this.attach_Fact_User_Alert_Groups), new Action<Fact_User_Alert_Group>(this.detach_Fact_User_Alert_Groups));
			this._Fact_User_Scenarios = new EntitySet<Fact_User_Scenario>(new Action<Fact_User_Scenario>(this.attach_Fact_User_Scenarios), new Action<Fact_User_Scenario>(this.detach_Fact_User_Scenarios));
			this._Fact_User_Analytics = new EntitySet<Fact_User_Analytic>(new Action<Fact_User_Analytic>(this.attach_Fact_User_Analytics), new Action<Fact_User_Analytic>(this.detach_Fact_User_Analytics));
			this._Fact_User_Canvas_Reports = new EntitySet<Fact_User_Canvas_Report>(new Action<Fact_User_Canvas_Report>(this.attach_Fact_User_Canvas_Reports), new Action<Fact_User_Canvas_Report>(this.detach_Fact_User_Canvas_Reports));
			this._Fact_User_Customers = new EntitySet<Fact_User_Customer>(new Action<Fact_User_Customer>(this.attach_Fact_User_Customers), new Action<Fact_User_Customer>(this.detach_Fact_User_Customers));
			this._Fact_User_Login_Logs = new EntitySet<Fact_User_Login_Log>(new Action<Fact_User_Login_Log>(this.attach_Fact_User_Login_Logs), new Action<Fact_User_Login_Log>(this.detach_Fact_User_Login_Logs));
			this._Fact_User_Products = new EntitySet<Fact_User_Product>(new Action<Fact_User_Product>(this.attach_Fact_User_Products), new Action<Fact_User_Product>(this.detach_Fact_User_Products));
			this._Fact_User_Promotion_Graphs = new EntitySet<Fact_User_Promotion_Graph>(new Action<Fact_User_Promotion_Graph>(this.attach_Fact_User_Promotion_Graphs), new Action<Fact_User_Promotion_Graph>(this.detach_Fact_User_Promotion_Graphs));
			this._Fact_User_Reports = new EntitySet<Fact_User_Report>(new Action<Fact_User_Report>(this.attach_Fact_User_Reports), new Action<Fact_User_Report>(this.detach_Fact_User_Reports));
			this._Fact_User_Roles = new EntitySet<Fact_User_Role>(new Action<Fact_User_Role>(this.attach_Fact_User_Roles), new Action<Fact_User_Role>(this.detach_Fact_User_Roles));
			this._Fact_User_SalesOrgs = new EntitySet<Fact_User_SalesOrg>(new Action<Fact_User_SalesOrg>(this.attach_Fact_User_SalesOrgs), new Action<Fact_User_SalesOrg>(this.detach_Fact_User_SalesOrgs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Idx", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Idx
		{
			get
			{
				return this._User_Idx;
			}
			set
			{
				if ((this._User_Idx != value))
				{
					this.OnUser_IdxChanging(value);
					this.SendPropertyChanging();
					this._User_Idx = value;
					this.SendPropertyChanged("User_Idx");
					this.OnUser_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_FirstName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string User_FirstName
		{
			get
			{
				return this._User_FirstName;
			}
			set
			{
				if ((this._User_FirstName != value))
				{
					this.OnUser_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._User_FirstName = value;
					this.SendPropertyChanged("User_FirstName");
					this.OnUser_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_LastName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string User_LastName
		{
			get
			{
				return this._User_LastName;
			}
			set
			{
				if ((this._User_LastName != value))
				{
					this.OnUser_LastNameChanging(value);
					this.SendPropertyChanging();
					this._User_LastName = value;
					this.SendPropertyChanged("User_LastName");
					this.OnUser_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_DisplayName", AutoSync=AutoSync.Always, DbType="VarChar(202) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string User_DisplayName
		{
			get
			{
				return this._User_DisplayName;
			}
			set
			{
				if ((this._User_DisplayName != value))
				{
					this.OnUser_DisplayNameChanging(value);
					this.SendPropertyChanging();
					this._User_DisplayName = value;
					this.SendPropertyChanged("User_DisplayName");
					this.OnUser_DisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string User_Email
		{
			get
			{
				return this._User_Email;
			}
			set
			{
				if ((this._User_Email != value))
				{
					this.OnUser_EmailChanging(value);
					this.SendPropertyChanging();
					this._User_Email = value;
					this.SendPropertyChanged("User_Email");
					this.OnUser_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_LoginName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string User_LoginName
		{
			get
			{
				return this._User_LoginName;
			}
			set
			{
				if ((this._User_LoginName != value))
				{
					this.OnUser_LoginNameChanging(value);
					this.SendPropertyChanging();
					this._User_LoginName = value;
					this.SendPropertyChanged("User_LoginName");
					this.OnUser_LoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_LoginPassword", DbType="NVarChar(MAX)")]
		public string User_LoginPassword
		{
			get
			{
				return this._User_LoginPassword;
			}
			set
			{
				if ((this._User_LoginPassword != value))
				{
					this.OnUser_LoginPasswordChanging(value);
					this.SendPropertyChanging();
					this._User_LoginPassword = value;
					this.SendPropertyChanged("User_LoginPassword");
					this.OnUser_LoginPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Hash", DbType="Char(100)")]
		public string User_Hash
		{
			get
			{
				return this._User_Hash;
			}
			set
			{
				if ((this._User_Hash != value))
				{
					this.OnUser_HashChanging(value);
					this.SendPropertyChanging();
					this._User_Hash = value;
					this.SendPropertyChanged("User_Hash");
					this.OnUser_HashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_SaltedPassword", DbType="VarChar(100)")]
		public string User_SaltedPassword
		{
			get
			{
				return this._User_SaltedPassword;
			}
			set
			{
				if ((this._User_SaltedPassword != value))
				{
					this.OnUser_SaltedPasswordChanging(value);
					this.SendPropertyChanging();
					this._User_SaltedPassword = value;
					this.SendPropertyChanged("User_SaltedPassword");
					this.OnUser_SaltedPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_UniqueCode", DbType="VarChar(10)")]
		public string User_UniqueCode
		{
			get
			{
				return this._User_UniqueCode;
			}
			set
			{
				if ((this._User_UniqueCode != value))
				{
					this.OnUser_UniqueCodeChanging(value);
					this.SendPropertyChanging();
					this._User_UniqueCode = value;
					this.SendPropertyChanged("User_UniqueCode");
					this.OnUser_UniqueCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ExcludeFromEmail_Workflow", DbType="Bit NOT NULL")]
		public bool User_ExcludeFromEmail_Workflow
		{
			get
			{
				return this._User_ExcludeFromEmail_Workflow;
			}
			set
			{
				if ((this._User_ExcludeFromEmail_Workflow != value))
				{
					this.OnUser_ExcludeFromEmail_WorkflowChanging(value);
					this.SendPropertyChanging();
					this._User_ExcludeFromEmail_Workflow = value;
					this.SendPropertyChanged("User_ExcludeFromEmail_Workflow");
					this.OnUser_ExcludeFromEmail_WorkflowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_AD_Name", DbType="VarChar(200)")]
		public string User_AD_Name
		{
			get
			{
				return this._User_AD_Name;
			}
			set
			{
				if ((this._User_AD_Name != value))
				{
					this.OnUser_AD_NameChanging(value);
					this.SendPropertyChanging();
					this._User_AD_Name = value;
					this.SendPropertyChanged("User_AD_Name");
					this.OnUser_AD_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnabled", DbType="Bit NOT NULL")]
		public bool IsEnabled
		{
			get
			{
				return this._IsEnabled;
			}
			set
			{
				if ((this._IsEnabled != value))
				{
					this.OnIsEnabledChanging(value);
					this.SendPropertyChanging();
					this._IsEnabled = value;
					this.SendPropertyChanged("IsEnabled");
					this.OnIsEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUserProfile", DbType="Bit NOT NULL")]
		public bool IsUserProfile
		{
			get
			{
				return this._IsUserProfile;
			}
			set
			{
				if ((this._IsUserProfile != value))
				{
					this.OnIsUserProfileChanging(value);
					this.SendPropertyChanging();
					this._IsUserProfile = value;
					this.SendPropertyChanged("IsUserProfile");
					this.OnIsUserProfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedProfile_Idx", DbType="Int")]
		public System.Nullable<int> AssignedProfile_Idx
		{
			get
			{
				return this._AssignedProfile_Idx;
			}
			set
			{
				if ((this._AssignedProfile_Idx != value))
				{
					this.OnAssignedProfile_IdxChanging(value);
					this.SendPropertyChanging();
					this._AssignedProfile_Idx = value;
					this.SendPropertyChanged("AssignedProfile_Idx");
					this.OnAssignedProfile_IdxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Language", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string User_Language
		{
			get
			{
				return this._User_Language;
			}
			set
			{
				if ((this._User_Language != value))
				{
					this.OnUser_LanguageChanging(value);
					this.SendPropertyChanging();
					this._User_Language = value;
					this.SendPropertyChanged("User_Language");
					this.OnUser_LanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SessionID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> SessionID
		{
			get
			{
				return this._SessionID;
			}
			set
			{
				if ((this._SessionID != value))
				{
					this.OnSessionIDChanging(value);
					this.SendPropertyChanging();
					this._SessionID = value;
					this.SendPropertyChanged("SessionID");
					this.OnSessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Alert_Group", Storage="_Fact_User_Alert_Groups", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Alert_Group> Fact_User_Alert_Groups
		{
			get
			{
				return this._Fact_User_Alert_Groups;
			}
			set
			{
				this._Fact_User_Alert_Groups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Scenario", Storage="_Fact_User_Scenarios", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Scenario> Fact_User_Scenarios
		{
			get
			{
				return this._Fact_User_Scenarios;
			}
			set
			{
				this._Fact_User_Scenarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Analytic", Storage="_Fact_User_Analytics", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Analytic> Fact_User_Analytics
		{
			get
			{
				return this._Fact_User_Analytics;
			}
			set
			{
				this._Fact_User_Analytics.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Canvas_Report", Storage="_Fact_User_Canvas_Reports", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Canvas_Report> Fact_User_Canvas_Reports
		{
			get
			{
				return this._Fact_User_Canvas_Reports;
			}
			set
			{
				this._Fact_User_Canvas_Reports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Customer", Storage="_Fact_User_Customers", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Customer> Fact_User_Customers
		{
			get
			{
				return this._Fact_User_Customers;
			}
			set
			{
				this._Fact_User_Customers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Login_Log", Storage="_Fact_User_Login_Logs", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Login_Log> Fact_User_Login_Logs
		{
			get
			{
				return this._Fact_User_Login_Logs;
			}
			set
			{
				this._Fact_User_Login_Logs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Product", Storage="_Fact_User_Products", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Product> Fact_User_Products
		{
			get
			{
				return this._Fact_User_Products;
			}
			set
			{
				this._Fact_User_Products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Promotion_Graph", Storage="_Fact_User_Promotion_Graphs", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Promotion_Graph> Fact_User_Promotion_Graphs
		{
			get
			{
				return this._Fact_User_Promotion_Graphs;
			}
			set
			{
				this._Fact_User_Promotion_Graphs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Report", Storage="_Fact_User_Reports", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Report> Fact_User_Reports
		{
			get
			{
				return this._Fact_User_Reports;
			}
			set
			{
				this._Fact_User_Reports.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_Role", Storage="_Fact_User_Roles", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_Role> Fact_User_Roles
		{
			get
			{
				return this._Fact_User_Roles;
			}
			set
			{
				this._Fact_User_Roles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dim_User_Fact_User_SalesOrg", Storage="_Fact_User_SalesOrgs", ThisKey="User_Idx", OtherKey="User_Idx")]
		public EntitySet<Fact_User_SalesOrg> Fact_User_SalesOrgs
		{
			get
			{
				return this._Fact_User_SalesOrgs;
			}
			set
			{
				this._Fact_User_SalesOrgs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fact_User_Alert_Groups(Fact_User_Alert_Group entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Alert_Groups(Fact_User_Alert_Group entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Scenarios(Fact_User_Scenario entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Scenarios(Fact_User_Scenario entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Analytics(Fact_User_Analytic entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Analytics(Fact_User_Analytic entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Canvas_Reports(Fact_User_Canvas_Report entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Canvas_Reports(Fact_User_Canvas_Report entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Customers(Fact_User_Customer entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Customers(Fact_User_Customer entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Login_Logs(Fact_User_Login_Log entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Login_Logs(Fact_User_Login_Log entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Products(Fact_User_Product entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Products(Fact_User_Product entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Promotion_Graphs(Fact_User_Promotion_Graph entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Promotion_Graphs(Fact_User_Promotion_Graph entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Reports(Fact_User_Report entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Reports(Fact_User_Report entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_Roles(Fact_User_Role entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_Roles(Fact_User_Role entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
		
		private void attach_Fact_User_SalesOrgs(Fact_User_SalesOrg entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = this;
		}
		
		private void detach_Fact_User_SalesOrgs(Fact_User_SalesOrg entity)
		{
			this.SendPropertyChanging();
			entity.Dim_User = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.SYS_Config")]
	public partial class SYS_Config : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OptionItem_ID;
		
		private string _OptionItem;
		
		private string _OptionItemDetail;
		
		private string _OptionItemDetail_Value;
		
		private string _Description;
		
		private bool _IsEditable;
		
		private string _MenuItem_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOptionItem_IDChanging(int value);
    partial void OnOptionItem_IDChanged();
    partial void OnOptionItemChanging(string value);
    partial void OnOptionItemChanged();
    partial void OnOptionItemDetailChanging(string value);
    partial void OnOptionItemDetailChanged();
    partial void OnOptionItemDetail_ValueChanging(string value);
    partial void OnOptionItemDetail_ValueChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsEditableChanging(bool value);
    partial void OnIsEditableChanged();
    partial void OnMenuItem_CodeChanging(string value);
    partial void OnMenuItem_CodeChanged();
    #endregion
		
		public SYS_Config()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItem_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OptionItem_ID
		{
			get
			{
				return this._OptionItem_ID;
			}
			set
			{
				if ((this._OptionItem_ID != value))
				{
					this.OnOptionItem_IDChanging(value);
					this.SendPropertyChanging();
					this._OptionItem_ID = value;
					this.SendPropertyChanged("OptionItem_ID");
					this.OnOptionItem_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItem", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OptionItem
		{
			get
			{
				return this._OptionItem;
			}
			set
			{
				if ((this._OptionItem != value))
				{
					this.OnOptionItemChanging(value);
					this.SendPropertyChanging();
					this._OptionItem = value;
					this.SendPropertyChanged("OptionItem");
					this.OnOptionItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItemDetail", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string OptionItemDetail
		{
			get
			{
				return this._OptionItemDetail;
			}
			set
			{
				if ((this._OptionItemDetail != value))
				{
					this.OnOptionItemDetailChanging(value);
					this.SendPropertyChanging();
					this._OptionItemDetail = value;
					this.SendPropertyChanged("OptionItemDetail");
					this.OnOptionItemDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionItemDetail_Value", DbType="NVarChar(4000)")]
		public string OptionItemDetail_Value
		{
			get
			{
				return this._OptionItemDetail_Value;
			}
			set
			{
				if ((this._OptionItemDetail_Value != value))
				{
					this.OnOptionItemDetail_ValueChanging(value);
					this.SendPropertyChanging();
					this._OptionItemDetail_Value = value;
					this.SendPropertyChanged("OptionItemDetail_Value");
					this.OnOptionItemDetail_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(4000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEditable", DbType="Bit NOT NULL")]
		public bool IsEditable
		{
			get
			{
				return this._IsEditable;
			}
			set
			{
				if ((this._IsEditable != value))
				{
					this.OnIsEditableChanging(value);
					this.SendPropertyChanging();
					this._IsEditable = value;
					this.SendPropertyChanged("IsEditable");
					this.OnIsEditableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItem_Code", DbType="VarChar(50)")]
		public string MenuItem_Code
		{
			get
			{
				return this._MenuItem_Code;
			}
			set
			{
				if ((this._MenuItem_Code != value))
				{
					this.OnMenuItem_CodeChanging(value);
					this.SendPropertyChanging();
					this._MenuItem_Code = value;
					this.SendPropertyChanged("MenuItem_Code");
					this.OnMenuItem_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
