//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.exceedra.org/", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name storedProcedureName from namespace http://webservice.exceedra.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.exceedra.org/Run", ReplyAction="*")]
        Model.ServiceReference1.RunResponse Run(Model.ServiceReference1.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://webservice.exceedra.org/Run", ReplyAction="*")]
        System.IAsyncResult BeginRun(Model.ServiceReference1.RunRequest request, System.AsyncCallback callback, object asyncState);
        
        Model.ServiceReference1.RunResponse EndRun(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://webservice.exceedra.org/", Order=0)]
        public Model.ServiceReference1.RunRequestBody Body;
        
        public RunRequest() {
        }
        
        public RunRequest(Model.ServiceReference1.RunRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.exceedra.org/")]
    public partial class RunRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storedProcedureName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parameters;
        
        public RunRequestBody() {
        }
        
        public RunRequestBody(string storedProcedureName, string parameters) {
            this.storedProcedureName = storedProcedureName;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://webservice.exceedra.org/", Order=0)]
        public Model.ServiceReference1.RunResponseBody Body;
        
        public RunResponse() {
        }
        
        public RunResponse(Model.ServiceReference1.RunResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.exceedra.org/")]
    public partial class RunResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunResult;
        
        public RunResponseBody() {
        }
        
        public RunResponseBody(string RunResult) {
            this.RunResult = RunResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Model.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Model.ServiceReference1.WebServiceSoap>, Model.ServiceReference1.WebServiceSoap {
        
        private BeginOperationDelegate onBeginRunDelegate;
        
        private EndOperationDelegate onEndRunDelegate;
        
        private System.Threading.SendOrPostCallback onRunCompletedDelegate;
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<RunCompletedEventArgs> RunCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Model.ServiceReference1.RunResponse Model.ServiceReference1.WebServiceSoap.Run(Model.ServiceReference1.RunRequest request) {
            return base.Channel.Run(request);
        }
        
        public string Run(string storedProcedureName, string parameters) {
            Model.ServiceReference1.RunRequest inValue = new Model.ServiceReference1.RunRequest();
            inValue.Body = new Model.ServiceReference1.RunRequestBody();
            inValue.Body.storedProcedureName = storedProcedureName;
            inValue.Body.parameters = parameters;
            Model.ServiceReference1.RunResponse retVal = ((Model.ServiceReference1.WebServiceSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Model.ServiceReference1.WebServiceSoap.BeginRun(Model.ServiceReference1.RunRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRun(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRun(string storedProcedureName, string parameters, System.AsyncCallback callback, object asyncState) {
            Model.ServiceReference1.RunRequest inValue = new Model.ServiceReference1.RunRequest();
            inValue.Body = new Model.ServiceReference1.RunRequestBody();
            inValue.Body.storedProcedureName = storedProcedureName;
            inValue.Body.parameters = parameters;
            return ((Model.ServiceReference1.WebServiceSoap)(this)).BeginRun(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Model.ServiceReference1.RunResponse Model.ServiceReference1.WebServiceSoap.EndRun(System.IAsyncResult result) {
            return base.Channel.EndRun(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndRun(System.IAsyncResult result) {
            Model.ServiceReference1.RunResponse retVal = ((Model.ServiceReference1.WebServiceSoap)(this)).EndRun(result);
            return retVal.Body.RunResult;
        }
        
        private System.IAsyncResult OnBeginRun(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string storedProcedureName = ((string)(inValues[0]));
            string parameters = ((string)(inValues[1]));
            return this.BeginRun(storedProcedureName, parameters, callback, asyncState);
        }
        
        private object[] OnEndRun(System.IAsyncResult result) {
            string retVal = this.EndRun(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRunCompleted(object state) {
            if ((this.RunCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RunCompleted(this, new RunCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RunAsync(string storedProcedureName, string parameters) {
            this.RunAsync(storedProcedureName, parameters, null);
        }
        
        public void RunAsync(string storedProcedureName, string parameters, object userState) {
            if ((this.onBeginRunDelegate == null)) {
                this.onBeginRunDelegate = new BeginOperationDelegate(this.OnBeginRun);
            }
            if ((this.onEndRunDelegate == null)) {
                this.onEndRunDelegate = new EndOperationDelegate(this.OnEndRun);
            }
            if ((this.onRunCompletedDelegate == null)) {
                this.onRunCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRunCompleted);
            }
            base.InvokeAsync(this.onBeginRunDelegate, new object[] {
                        storedProcedureName,
                        parameters}, this.onEndRunDelegate, this.onRunCompletedDelegate, userState);
        }
    }
}
