//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.ResourceLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.ResourceLib.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string Button_AddComment {
            get {
                return ResourceManager.GetString("Button_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Match.
        /// </summary>
        internal static string Button_AutomaticallyMatch {
            get {
                return ResourceManager.GetString("Button_AutomaticallyMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Condition.
        /// </summary>
        internal static string Button_CreateNewCOndition {
            get {
                return ResourceManager.GetString("Button_CreateNewCOndition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Volumes.
        /// </summary>
        internal static string Button_DailyVolumes {
            get {
                return ResourceManager.GetString("Button_DailyVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Match.
        /// </summary>
        internal static string Button_ManualMatch {
            get {
                return ResourceManager.GetString("Button_ManualMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Report.
        /// </summary>
        internal static string Button_OpenReport {
            get {
                return ResourceManager.GetString("Button_OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Button_Payment {
            get {
                return ResourceManager.GetString("Button_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasing.
        /// </summary>
        internal static string Button_Phasing {
            get {
                return ResourceManager.GetString("Button_Phasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Chart.
        /// </summary>
        internal static string Button_RefreshChart {
            get {
                return ResourceManager.GetString("Button_RefreshChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Button_Replace {
            get {
                return ResourceManager.GetString("Button_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        internal static string Button_SaveClose {
            get {
                return ResourceManager.GetString("Button_SaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Defaults.
        /// </summary>
        internal static string Button_SaveDefault {
            get {
                return ResourceManager.GetString("Button_SaveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Filters.
        /// </summary>
        internal static string Button_SaveFilters {
            get {
                return ResourceManager.GetString("Button_SaveFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Button_SelectAll {
            get {
                return ResourceManager.GetString("Button_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Budgets.
        /// </summary>
        internal static string Button_UpdateBudgets {
            get {
                return ResourceManager.GetString("Button_UpdateBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Volumes.
        /// </summary>
        internal static string Button_WeeklyVolumes {
            get {
                return ResourceManager.GetString("Button_WeeklyVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value.
        /// </summary>
        internal static string Claim_ClaimValue {
            get {
                return ResourceManager.GetString("Claim_ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apportioned Amount.
        /// </summary>
        internal static string Column_ApportionedAmount {
            get {
                return ResourceManager.GetString("Column_ApportionedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Column_Author {
            get {
                return ResourceManager.GetString("Column_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Accrual.
        /// </summary>
        internal static string Column_AvailableAccrual {
            get {
                return ResourceManager.GetString("Column_AvailableAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Apportionment.
        /// </summary>
        internal static string Column_ClaimApportionment {
            get {
                return ResourceManager.GetString("Column_ClaimApportionment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Date.
        /// </summary>
        internal static string Column_ClaimDate {
            get {
                return ResourceManager.GetString("Column_ClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Line Detail.
        /// </summary>
        internal static string Column_ClaimLineDetail {
            get {
                return ResourceManager.GetString("Column_ClaimLineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Reference.
        /// </summary>
        internal static string Column_ClaimReference {
            get {
                return ResourceManager.GetString("Column_ClaimReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Date.
        /// </summary>
        internal static string Column_EnteredDate {
            get {
                return ResourceManager.GetString("Column_EnteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event End Date.
        /// </summary>
        internal static string Column_EventEndDate {
            get {
                return ResourceManager.GetString("Column_EventEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string Column_EventName {
            get {
                return ResourceManager.GetString("Column_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Start Date.
        /// </summary>
        internal static string Column_EventStartDate {
            get {
                return ResourceManager.GetString("Column_EventStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Status.
        /// </summary>
        internal static string Column_EventStatus {
            get {
                return ResourceManager.GetString("Column_EventStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string Column_EventType {
            get {
                return ResourceManager.GetString("Column_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched.
        /// </summary>
        internal static string Column_Matched {
            get {
                return ResourceManager.GetString("Column_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Accrual.
        /// </summary>
        internal static string Column_RemainingAccrual {
            get {
                return ResourceManager.GetString("Column_RemainingAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settled.
        /// </summary>
        internal static string Column_Settled {
            get {
                return ResourceManager.GetString("Column_Settled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Column_Status {
            get {
                return ResourceManager.GetString("Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accrual.
        /// </summary>
        internal static string Column_TotalAccrual {
            get {
                return ResourceManager.GetString("Column_TotalAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Sub Type.
        /// </summary>
        internal static string Colun_EventSubType {
            get {
                return ResourceManager.GetString("Colun_EventSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Change £.
        /// </summary>
        internal static string Label_AbsoluteChange {
            get {
                return ResourceManager.GetString("Label_AbsoluteChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string Label_AddComment {
            get {
                return ResourceManager.GetString("Label_AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Report.
        /// </summary>
        internal static string Label_AddNewReport {
            get {
                return ResourceManager.GetString("Label_AddNewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        internal static string Label_AddNote {
            get {
                return ResourceManager.GetString("Label_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string Label_Adjustment {
            get {
                return ResourceManager.GetString("Label_Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string Label_Approval {
            get {
                return ResourceManager.GetString("Label_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Trace.
        /// </summary>
        internal static string Label_AppTrace {
            get {
                return ResourceManager.GetString("Label_AppTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Label_Attributes {
            get {
                return ResourceManager.GetString("Label_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Cubes.
        /// </summary>
        internal static string Label_AvailableCubes {
            get {
                return ResourceManager.GetString("Label_AvailableCubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Profile Customer.
        /// </summary>
        internal static string Label_BaseProfileCustomer {
            get {
                return ResourceManager.GetString("Label_BaseProfileCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseSalesProduct.
        /// </summary>
        internal static string Label_BaseSalesProduct {
            get {
                return ResourceManager.GetString("Label_BaseSalesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Template.
        /// </summary>
        internal static string Label_BaseTemplate {
            get {
                return ResourceManager.GetString("Label_BaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings Date.
        /// </summary>
        internal static string Label_Bindings_Date {
            get {
                return ResourceManager.GetString("Label_Bindings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Scan.
        /// </summary>
        internal static string Label_ChangeScan {
            get {
                return ResourceManager.GetString("Label_ChangeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Date.
        /// </summary>
        internal static string Label_ClaimDate {
            get {
                return ResourceManager.GetString("Label_ClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Entry.
        /// </summary>
        internal static string Label_ClaimEntry {
            get {
                return ResourceManager.GetString("Label_ClaimEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Line Detail.
        /// </summary>
        internal static string Label_ClaimLineDetail {
            get {
                return ResourceManager.GetString("Label_ClaimLineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Status.
        /// </summary>
        internal static string Label_ClaimStatus {
            get {
                return ResourceManager.GetString("Label_ClaimStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value Ranges.
        /// </summary>
        internal static string Label_ClaimValueRanges {
            get {
                return ResourceManager.GetString("Label_ClaimValueRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Label_Code {
            get {
                return ResourceManager.GetString("Label_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label_CodeBehind_Callback {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label_CodeBehind_Format {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label_CodeBehind_Resource {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Label_CodeBehind_ResourceFormat {
            get {
                return ResourceManager.GetString("Label_CodeBehind_ResourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Type.
        /// </summary>
        internal static string Label_ConditionType {
            get {
                return ResourceManager.GetString("Label_ConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Label_Customer {
            get {
                return ResourceManager.GetString("Label_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Level.
        /// </summary>
        internal static string Label_CustomerLevel {
            get {
                return ResourceManager.GetString("Label_CustomerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Label_Customers {
            get {
                return ResourceManager.GetString("Label_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSourced.
        /// </summary>
        internal static string Label_DataSources {
            get {
                return ResourceManager.GetString("Label_DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string Label_Dates {
            get {
                return ResourceManager.GetString("Label_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string Label_DefaultValue {
            get {
                return ResourceManager.GetString("Label_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Current Report.
        /// </summary>
        internal static string Label_DeleteCurrentReport {
            get {
                return ResourceManager.GetString("Label_DeleteCurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Current Report.
        /// </summary>
        internal static string Label_EditCurrentReport {
            get {
                return ResourceManager.GetString("Label_EditCurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        internal static string Label_EventDate {
            get {
                return ResourceManager.GetString("Label_EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string Label_EventName {
            get {
                return ResourceManager.GetString("Label_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Label_Events {
            get {
                return ResourceManager.GetString("Label_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Status.
        /// </summary>
        internal static string Label_EventStatus {
            get {
                return ResourceManager.GetString("Label_EventStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Sub Type.
        /// </summary>
        internal static string Label_EventSubType {
            get {
                return ResourceManager.GetString("Label_EventSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        internal static string Label_EventType {
            get {
                return ResourceManager.GetString("Label_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Label_Export {
            get {
                return ResourceManager.GetString("Label_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        internal static string Label_FilterBy {
            get {
                return ResourceManager.GetString("Label_FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Label_Filters {
            get {
                return ResourceManager.GetString("Label_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Label_Flag {
            get {
                return ResourceManager.GetString("Label_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heirarchial.
        /// </summary>
        internal static string Label_Heirarchial {
            get {
                return ResourceManager.GetString("Label_Heirarchial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impacts.
        /// </summary>
        internal static string Label_Impacts {
            get {
                return ResourceManager.GetString("Label_Impacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string Label_Interval {
            get {
                return ResourceManager.GetString("Label_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Adjustment.
        /// </summary>
        internal static string Label_InvalidAdjustment {
            get {
                return ResourceManager.GetString("Label_InvalidAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active Budget.
        /// </summary>
        internal static string Label_IsActiveBudget {
            get {
                return ResourceManager.GetString("Label_IsActiveBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Label_Item {
            get {
                return ResourceManager.GetString("Label_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaf.
        /// </summary>
        internal static string Label_Leaf {
            get {
                return ResourceManager.GetString("Label_Leaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching.
        /// </summary>
        internal static string Label_Matching {
            get {
                return ResourceManager.GetString("Label_Matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Status.
        /// </summary>
        internal static string Label_MatchingStatus {
            get {
                return ResourceManager.GetString("Label_MatchingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasureList.
        /// </summary>
        internal static string Label_MeasureList {
            get {
                return ResourceManager.GetString("Label_MeasureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Lists.
        /// </summary>
        internal static string Label_MeasureLists {
            get {
                return ResourceManager.GetString("Label_MeasureLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Filters.
        /// </summary>
        internal static string Label_MyFilters {
            get {
                return ResourceManager.GetString("Label_MyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Value.
        /// </summary>
        internal static string Label_NetValue {
            get {
                return ResourceManager.GetString("Label_NetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Label_Notes {
            get {
                return ResourceManager.GetString("Label_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD Products.
        /// </summary>
        internal static string Label_NPDProducts {
            get {
                return ResourceManager.GetString("Label_NPDProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentDate.
        /// </summary>
        internal static string Label_PaymentDate {
            get {
                return ResourceManager.GetString("Label_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage change %.
        /// </summary>
        internal static string Label_PercentageChange {
            get {
                return ResourceManager.GetString("Label_PercentageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Label_Period {
            get {
                return ResourceManager.GetString("Label_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined.
        /// </summary>
        internal static string Label_Predefined {
            get {
                return ResourceManager.GetString("Label_Predefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Level.
        /// </summary>
        internal static string Label_ProductLevel {
            get {
                return ResourceManager.GetString("Label_ProductLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Parent.
        /// </summary>
        internal static string Label_ProductParent {
            get {
                return ResourceManager.GetString("Label_ProductParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Label_Products {
            get {
                return ResourceManager.GetString("Label_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Filter.
        /// </summary>
        internal static string Label_QuickFilter {
            get {
                return ResourceManager.GetString("Label_QuickFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Change.
        /// </summary>
        internal static string Label_ReasonForChange {
            get {
                return ResourceManager.GetString("Label_ReasonForChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        internal static string Label_Recipient {
            get {
                return ResourceManager.GetString("Label_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Label_Replace {
            get {
                return ResourceManager.GetString("Label_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace NPD Product.
        /// </summary>
        internal static string Label_ReplaceNPDProduct {
            get {
                return ResourceManager.GetString("Label_ReplaceNPDProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Matches.
        /// </summary>
        internal static string Label_ReviewMatches {
            get {
                return ResourceManager.GetString("Label_ReviewMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Org.
        /// </summary>
        internal static string Label_SalesOrg {
            get {
                return ResourceManager.GetString("Label_SalesOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Organisation.
        /// </summary>
        internal static string Label_SalesOrganisations {
            get {
                return ResourceManager.GetString("Label_SalesOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Location.
        /// </summary>
        internal static string Label_ScanLocation {
            get {
                return ResourceManager.GetString("Label_ScanLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string Label_Scenario {
            get {
                return ResourceManager.GetString("Label_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Claim Date.
        /// </summary>
        internal static string Label_SearchClaimDate {
            get {
                return ResourceManager.GetString("Label_SearchClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Entered Date.
        /// </summary>
        internal static string Label_SearchEnteredDate {
            get {
                return ResourceManager.GetString("Label_SearchEnteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Label_SelectAll {
            get {
                return ResourceManager.GetString("Label_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Label_Selection {
            get {
                return ResourceManager.GetString("Label_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Settings.
        /// </summary>
        internal static string Label_SelectionSettings {
            get {
                return ResourceManager.GetString("Label_SelectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All From.
        /// </summary>
        internal static string Label_SetAllFrom {
            get {
                return ResourceManager.GetString("Label_SetAllFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All To.
        /// </summary>
        internal static string Label_SetAllTo {
            get {
                return ResourceManager.GetString("Label_SetAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Values.
        /// </summary>
        internal static string Label_SetAllValues {
            get {
                return ResourceManager.GetString("Label_SetAllValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All Values %.
        /// </summary>
        internal static string Label_SetAllValuesPercentage {
            get {
                return ResourceManager.GetString("Label_SetAllValuesPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Exact Value £.
        /// </summary>
        internal static string Label_SetExactValue {
            get {
                return ResourceManager.GetString("Label_SetExactValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settled.
        /// </summary>
        internal static string Label_Settled {
            get {
                return ResourceManager.GetString("Label_Settled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Child Customers &amp; Products:.
        /// </summary>
        internal static string Label_ShowChildCustProds {
            get {
                return ResourceManager.GetString("Label_ShowChildCustProds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Zero Apportionments.
        /// </summary>
        internal static string Label_ShowZeroAppointments {
            get {
                return ResourceManager.GetString("Label_ShowZeroAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Label_Single {
            get {
                return ResourceManager.GetString("Label_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Label_Start {
            get {
                return ResourceManager.GetString("Label_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is before the 
        ///start date. Please select valid dates..
        /// </summary>
        internal static string Label_StartAfterEndError {
            get {
                return ResourceManager.GetString("Label_StartAfterEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Type.
        /// </summary>
        internal static string Label_SubType {
            get {
                return ResourceManager.GetString("Label_SubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Selection.
        /// </summary>
        internal static string Label_TimeSelection {
            get {
                return ResourceManager.GetString("Label_TimeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Accrual.
        /// </summary>
        internal static string Label_TotalAccrual {
            get {
                return ResourceManager.GetString("Label_TotalAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Adjustment.
        /// </summary>
        internal static string Label_TotalAdjustment {
            get {
                return ResourceManager.GetString("Label_TotalAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Budgets.
        /// </summary>
        internal static string Label_UpdateBudgets {
            get {
                return ResourceManager.GetString("Label_UpdateBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Label_Users {
            get {
                return ResourceManager.GetString("Label_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Label_Value {
            get {
                return ResourceManager.GetString("Label_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Label_Variables {
            get {
                return ResourceManager.GetString("Label_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Location.
        /// </summary>
        internal static string Label_ViewLocation {
            get {
                return ResourceManager.GetString("Label_ViewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Adjust.
        /// </summary>
        internal static string Label_VolumeAdjust {
            get {
                return ResourceManager.GetString("Label_VolumeAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What.
        /// </summary>
        internal static string Label_What {
            get {
                return ResourceManager.GetString("Label_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string Label_When {
            get {
                return ResourceManager.GetString("Label_When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string Label_Where {
            get {
                return ResourceManager.GetString("Label_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Real Products.
        /// </summary>
        internal static string Label_WithRealProduct {
            get {
                return ResourceManager.GetString("Label_WithRealProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Reports.
        /// </summary>
        internal static string Label_YourReports {
            get {
                return ResourceManager.GetString("Label_YourReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help email help@exceedra.com.
        /// </summary>
        internal static string Login_label_EmailSupport {
            get {
                return ResourceManager.GetString("Login_label_EmailSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_label_Password {
            get {
                return ResourceManager.GetString("Login_label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string Login_label_Remember {
            get {
                return ResourceManager.GetString("Login_label_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Login.
        /// </summary>
        internal static string Login_label_Title {
            get {
                return ResourceManager.GetString("Login_label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_label_Username {
            get {
                return ResourceManager.GetString("Login_label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using authentication.
        /// </summary>
        internal static string Login_label_WithAuthentication {
            get {
                return ResourceManager.GetString("Login_label_WithAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Margin_Style {
            get {
                return ResourceManager.GetString("Margin_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Menu_Admin {
            get {
                return ResourceManager.GetString("Menu_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Menu_Analytics {
            get {
                return ResourceManager.GetString("Menu_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        internal static string Menu_Claims {
            get {
                return ResourceManager.GetString("Menu_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string Menu_Conditions {
            get {
                return ResourceManager.GetString("Menu_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funds.
        /// </summary>
        internal static string Menu_Funds {
            get {
                return ResourceManager.GetString("Menu_Funds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        internal static string Menu_Insights {
            get {
                return ResourceManager.GetString("Menu_Insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Menu_LogOut {
            get {
                return ResourceManager.GetString("Menu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPD.
        /// </summary>
        internal static string Menu_NPD {
            get {
                return ResourceManager.GetString("Menu_NPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        internal static string Menu_Planning {
            get {
                return ResourceManager.GetString("Menu_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string Menu_Pricing {
            get {
                return ResourceManager.GetString("Menu_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        internal static string Menu_Promotions {
            get {
                return ResourceManager.GetString("Menu_Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks &amp; Ops.
        /// </summary>
        internal static string Menu_Risks_Ops {
            get {
                return ResourceManager.GetString("Menu_Risks_Ops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        internal static string Menu_Scenarios {
            get {
                return ResourceManager.GetString("Menu_Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Menu_Schedule {
            get {
                return ResourceManager.GetString("Menu_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys.
        /// </summary>
        internal static string Menu_Sys {
            get {
                return ResourceManager.GetString("Menu_Sys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Menu_Terms {
            get {
                return ResourceManager.GetString("Menu_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ribbon_Add {
            get {
                return ResourceManager.GetString("Ribbon_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Ribbon_Delete {
            get {
                return ResourceManager.GetString("Ribbon_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Ribbon_Filters {
            get {
                return ResourceManager.GetString("Ribbon_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Default.
        /// </summary>
        internal static string Ribbon_SaveDefault {
            get {
                return ResourceManager.GetString("Ribbon_SaveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search/Filters.
        /// </summary>
        internal static string Watermark_Filters {
            get {
                return ResourceManager.GetString("Watermark_Filters", resourceCulture);
            }
        }
    }
}
