//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=exceedracom.cloudapp.net,10315;Initial Catalog=ESP_Demo_DEV_UK_v2_9;U" +
            "ser ID=WebApp;password=ExceedraLondon1!")]
        public string ESP_Demo_DEV_UK_v2_9ConnectionString {
            get {
                return ((string)(this["ESP_Demo_DEV_UK_v2_9ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=exceedracom.cloudapp.net,10315;Initial Catalog=ESP_Demo_DEV_UK_v2_9;U" +
            "ser ID=WebApp;password=ExceedraLondon1!;Connect Timeout=60")]
        public string ESP_Demo_DEV_UK_v2_9ConnectionString1 {
            get {
                return ((string)(this["ESP_Demo_DEV_UK_v2_9ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=exceedracom.cloudapp.net,10315;Initial Catalog=ESP_Demo_DEV_UK_v2_9;U" +
            "ser ID=WebApp;Password=ExceedraLondon1!;Connect Timeout=60")]
        public string ESP_Demo_DEV_UK_v2_9ConnectionString2 {
            get {
                return ((string)(this["ESP_Demo_DEV_UK_v2_9ConnectionString2"]));
            }
        }
    }
}
